default_addAd:
    path:     /add
    defaults: { _controller: zelakiouiAdsProjectBundle:Ad:addAd}

default_successAddAd:
    path:     /success
    defaults: { _controller: zelakiouiAdsProjectBundle:Ad:successAddAd}

client_addAdd:
    path:     /client/add
    defaults: { _controller: zelakiouiAdsProjectBundle:AdClient:addAd}
